#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fcoe-utils
Version  : 1.0.33
Release  : 4
URL      : https://github.com/morbidrsa/fcoe-utils/archive/v1.0.33/fcoe-utils-1.0.33.tar.gz
Source0  : https://github.com/morbidrsa/fcoe-utils/archive/v1.0.33/fcoe-utils-1.0.33.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: fcoe-utils-bin = %{version}-%{release}
Requires: fcoe-utils-data = %{version}-%{release}
Requires: fcoe-utils-license = %{version}-%{release}
Requires: fcoe-utils-man = %{version}-%{release}
Requires: fcoe-utils-services = %{version}-%{release}
BuildRequires : pkgconfig(lldpad)
BuildRequires : pkgconfig(pciaccess)
BuildRequires : pkgconfig(systemd)

%description
FCoE Management Tools Installation Guide
========================================

%package bin
Summary: bin components for the fcoe-utils package.
Group: Binaries
Requires: fcoe-utils-data = %{version}-%{release}
Requires: fcoe-utils-license = %{version}-%{release}
Requires: fcoe-utils-services = %{version}-%{release}

%description bin
bin components for the fcoe-utils package.


%package data
Summary: data components for the fcoe-utils package.
Group: Data

%description data
data components for the fcoe-utils package.


%package license
Summary: license components for the fcoe-utils package.
Group: Default

%description license
license components for the fcoe-utils package.


%package man
Summary: man components for the fcoe-utils package.
Group: Default

%description man
man components for the fcoe-utils package.


%package services
Summary: services components for the fcoe-utils package.
Group: Systemd services

%description services
services components for the fcoe-utils package.


%prep
%setup -q -n fcoe-utils-1.0.33
cd %{_builddir}/fcoe-utils-1.0.33

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1591755747
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1591755747
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fcoe-utils
cp %{_builddir}/fcoe-utils-1.0.33/COPYING %{buildroot}/usr/share/package-licenses/fcoe-utils/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fcnsq
/usr/bin/fcoeadm
/usr/bin/fcoemon
/usr/bin/fcping
/usr/bin/fcrls
/usr/bin/fipvlan

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/fcoeadm
/usr/share/bash-completion/completions/fcoemon

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fcoe-utils/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/fcnsq.8
/usr/share/man/man8/fcoeadm.8
/usr/share/man/man8/fcoemon.8
/usr/share/man/man8/fcping.8
/usr/share/man/man8/fcrls.8
/usr/share/man/man8/fipvlan.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/fcoe.service
/usr/lib/systemd/system/fcoemon.socket
