#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fcoe-utils
Version  : 1.0.32
Release  : 1
URL      : https://github.com/morbidrsa/fcoe-utils/archive/v1.0.32.tar.gz
Source0  : https://github.com/morbidrsa/fcoe-utils/archive/v1.0.32.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: fcoe-utils-bin = %{version}-%{release}
Requires: fcoe-utils-license = %{version}-%{release}
Requires: fcoe-utils-man = %{version}-%{release}
Requires: fcoe-utils-services = %{version}-%{release}
BuildRequires : pkgconfig(lldpad)
BuildRequires : pkgconfig(pciaccess)
BuildRequires : pkgconfig(systemd)
BuildRequires : systemd-dev

%description
FCoE Management Tools Installation Guide
========================================

%package bin
Summary: bin components for the fcoe-utils package.
Group: Binaries
Requires: fcoe-utils-license = %{version}-%{release}
Requires: fcoe-utils-man = %{version}-%{release}
Requires: fcoe-utils-services = %{version}-%{release}

%description bin
bin components for the fcoe-utils package.


%package license
Summary: license components for the fcoe-utils package.
Group: Default

%description license
license components for the fcoe-utils package.


%package man
Summary: man components for the fcoe-utils package.
Group: Default

%description man
man components for the fcoe-utils package.


%package services
Summary: services components for the fcoe-utils package.
Group: Systemd services

%description services
services components for the fcoe-utils package.


%prep
%setup -q -n fcoe-utils-1.0.32

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550094346
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1550094346
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fcoe-utils
cp COPYING %{buildroot}/usr/share/package-licenses/fcoe-utils/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fcnsq
/usr/bin/fcoeadm
/usr/bin/fcoemon
/usr/bin/fcping
/usr/bin/fcrls
/usr/bin/fipvlan

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fcoe-utils/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/fcnsq.8
/usr/share/man/man8/fcoeadm.8
/usr/share/man/man8/fcoemon.8
/usr/share/man/man8/fcping.8
/usr/share/man/man8/fcrls.8
/usr/share/man/man8/fipvlan.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/fcoe.service
/usr/lib/systemd/system/fcoemon.socket
